{ pkgs, inputs, ... }:

{
  environment.systemPackages =
    let
      sugar = pkgs.callPackage ./sddm-themes/sddm-sugar-dark.nix { };
      tokyo-night = pkgs.libsForQt5.callPackage ./sddm-themes/sddm-tokyo-night.nix { };
    in
    with pkgs;
    [
      vim
      wget
      git
      (pkgs.callPackage ./sddm-themes/sddm-astronaut-theme.nix {
        #theme = "hyprland_kath";
        theme = "jake_the_dog";
        themeConfig = {
          General = {
            HeaderText = "Hi!";
            #Background = "/home/user/Desktop/wp.png";
            FontSize = "25.0";
          };
        };
      })
      gparted
      nmap
      inputs.hyprswitch.packages.x86_64-linux.default
      xwayland-satellite
      xwayland-run
      hping
      q
      nextcloud-client
      rename
      # ollama-rocm
      nil
      spotdl
      mopidy
      mopidy-soundcloud
      ffmpeg
      pipx
      cosmic-edit
      cosmic-files
      snowflake
      openvpn
      inetutils
      sony-headphones-client
      telegram-desktop
      ffuf
      wordlists
      pritunl-client
      batmon
      vivaldi
      disko
      gnome-disk-utility
      nix-prefetch-github
      lazygit
      wapiti
      exiftool
      catppuccin
      seatd
      nixd
      code-cursor
      xdg-utils
      devenv
      binwalk
      thefuck
      sqlmap
      skypeforlinux
      hashcat
      popsicle
      overlayed
      hyprcursor
      osu-lazer-bin
      # bottles
      wmutils-core
      gopls
      go
      firefox-devedition
      ncdu
      mupdf
      nwg-look
      # calibre
      qalculate-qt
      direnv
      xdotool
      zenith
      ntfs3g
      opendrop
      nomacs
      adwaita-icon-theme
      adwaita-qt
      adwsteamgtk
      psmisc
      amf
      vaapi-intel-hybrid
      libva
      libva-vdpau-driver
      libva-utils
      #ladybird
      mesa
      vdpauinfo
      jq
      amdenc
      amd-blis
      youtube-tui
      bilibili
      amdgpu_top
      # qq
      microcode-amd
      zenmonitor
      stress
      virtualbox
      getent
      iconv
      glibc_memusage
      alsa-utils
      ventoy-full
      minecraft
      gamescope
      gamescope-wsi
      clinfo
      tailscale
      vesktop
      jstest-gtk
      linuxConsoleTools
      metasploit
      tcpreplay
      evhz
      cmatrix
      mcrcon
      lolcat
      jellyfin-media-player
      tor-browser
      neofetch
      htop
      gnome-boxes
      libsForQt5.qt5.qtquickcontrols2
      libsForQt5.qt5.qtgraphicaleffects
      libsForQt5.qt5ct
      kdePackages.qt6ct
      libvirt
      lxqt.lxqt-policykit
      logisim-evolution
      stdenv.cc.cc.lib
      stdenv
      libcxx
      libgcc
      gnat
      glibc
      mangohud
      blueman
      lm_sensors
      unzip
      bluez
      unrar
      libnotify
      rpi-imager
      eza
      v4l-utils
      ydotool
      wl-clipboard
      lm_sensors
      pciutils
      socat
      cowsay
      ripgrep
      lsd
      lshw
      pkg-config
      meson
      gnumake
      ninja
      symbola
      noto-fonts-color-emoji
      material-icons
      brightnessctl
      virt-viewer
      swappy
      rofi-wayland
      appimage-run
      networkmanagerapplet
      yad
      python311Full
      python312Full
      python3Full
      python311Packages.pip
      python312Packages.pip
      python311Packages.django
      jupyter
      playerctl
      nh
      nixfmt-rfc-style
      discord
      libvirt
      swww
      hyprpaper
      swaybg
      # nodePackages_latest.webtorrent-cli
      webtorrent_desktop
      clash-verge-rev
      grim
      hypridle
      waypaper
      nodejs_22
      nodejs_20
      nodejs_18
      heroic
      vlc
      neovim-qt
      neovim
      gnome-power-manager
      dmenu
      tesseract
      cliphist
      slurp
      file-roller
      swaynotificationcenter
      imv
      transmission_3-gtk
      transmission_4-gtk
      distrobox
      mpv
      vlc
      smplayer
      gimp
      rustup
      audacity
      pavucontrol
      tree
      protonup-qt
      font-awesome
      neovide
      nerd-fonts.jetbrains-mono
      sugar.sddm-sugar-dark # Name: sugar-dark
      tokyo-night # Name: tokyo-night-sddm
      pkgs.libsForQt5.qt5.qtgraphicaleffects
      wine
      wine64
      winetricks
      wine-wayland
      winePackages.stableFull
      winePackages.waylandFull
      wine64Packages.stableFull
      wine64Packages.waylandFull
      wineWowPackages.stableFull
      wineWowPackages.waylandFull
      wineWow64Packages.stableFull
      wineWow64Packages.waylandFull
      git
      gh
      unzip
      zip
      gnome-tweaks
      obsidian
      zed-editor
      miru
      ani-cli
      spotify
      krita
      btop
      lutris
      htop
      cmake
      gnumake
      tree
      thunderbird
      cargo
      vscode-fhs
      libreoffice
      wechat-uos
      okular
      discord
      uwufetch
      waydroid
      gcc
      gcc-unwrapped
      ibus
      ibus-with-plugins
      ibus-engines.rime
      ibus-theme-tools
      xorg.xdpyinfo
      winePackages.fonts
      wine64Packages.fonts
      wineWowPackages.fonts
      wineWow64Packages.fonts
      heroic
      prismlauncher
      fastfetch
      vim
      sl
    ];

  nixpkgs.config.permittedInsecurePackages = [
    "openssl-1.1.1w"
    "electron-27.3.11"
    "electron-30.5.1"
  ];

  nixpkgs.config.allowUnsupportedSystem = true;
  nixpkgs.config.allowBroken = true;
}
